.\" Manpage for ecocrumb.
.TH ecocrumb 1 "12 May 2023" "1.0" "ecocrumb man page"
.SH NAME
ecocrumb \- Process target directories, convert PDFs to plaintext, generate topics_features.json and parsed_sections.json
.SH SYNOPSIS
.B ecocrumb
[\-\-force] [\-\-batch] [\-\-train] <target_directory> [num_topics]
.SH DESCRIPTION
The \fBecocrumb\fR script is a utility for processing target directories, converting PDFs to plaintext files, and generating topics_features.json and parsed_sections.json files. It provides options to force regeneration of files, batch process multiple folders, and run the generate_topics.sh script.
.SH OPTIONS
.TP
.B \-\-force
Forces regeneration of the topics_features.json and parsed_sections.json files, even if they already exist.
.TP
.B \-\-batch
Processes each folder within the target_directory separately.
.TP
.B \-\-train
Enable train if you wish to update the choice of topics before running the model. Topics can be via the 'pick_esg_topics.csv' file. Once updated this flag will automatically incorporate changes.
.SH ARGUMENTS
.TP
.B <target_directory>
The company data directory or path to the set of copmany directories to be processed.
.TP
.B [num_topics]
The number of topics to generate. Default value: 15. Recommend less than 100.
.SH EXAMPLES
.TP
.B 1.
Process a single target directory:
.PP
\fB$ ecocrumb data/Starbucks\fR
.TP
.B 2.
Process a target directory with a specific number of topics:
.PP
\fB$ ecocrumb data/Starbucks 10\fR
.TP
.B 3.
Force regeneration and process a target directory:
.PP
\fB$ ecocrumb \-\-force data/Starbucks\fR
.TP
.B 4.
Batch process multiple folders within a target directory:
.PP
\fB$ ecocrumb \-\-batch data\fR
.TP
.B 5.
Enable training mode and process a target directory:
.PP
\fB$ ecocrumb \-\-train data/Starbucks\fR
.SH NOTES
.TP
\- The script requires the esgetlpipeline scripts to be present in the same directory as the ecocrumb script.
.TP
\- The output directories 'topics_features' and 'parsed_sections' will be created within the target_directory.
.TP
\- The 'plaintext' directory will be created within the target_directory to store converted plaintext files.
.TP
\- The 'results/' and 'esg_LanguageModel/src/' directories will be created within the directory where the ecocrumb script is located, and the parsed_sections files will be copied to those directories.
.SH AUTHOR
Written by Jude Safo, Haiphen Inc. 2023
.\" Generated by Ronn/v0.7.3

